### ISSUE TITLE
AnotherStorageImplementation example and BBMD..?

### ISSUE THREAD

**Issue by yltsa** [ela-compil/BACnet.Examples#4]
Hi,

Thank you very much for the great library. I made an application based on the AnotherStorageImplementation project. 

Now the problem is that I have to add BBMD support and cannot make it. The BBMD example uses a different approach and have not succeeded to integrate the BBMD.

All my BACnet devices are created dynamically from the SQL server and the AnotherStorageImplementation example is great for that. Please, can you help to integrate the BBMD into it? This is my first BACnet project..

Thank you :-)
Ilkka

**Comment by gralin** [comment]
Hi @yltsa, can you elaborate more on your use case? Are you trying to send/receive data from another network through BBMD or are you attempting to implement BBMD yourself?

**Comment by yltsa** [comment]
Hi,

I made a Modbus interface for controlling some devices. Now my colleague wants to control the same devices but he has no Modbus. Only BACnet.

So I integrated BACnet library in my application. It works OK in the same network by using YABE. But my colleague´s device in in other network. He said that I must make BBMD so that he can access the devices.

I actually succeed today to run the BAC BBMD example program separately. But is it possible to integrate BBMD into the application which uses similar structure is in the AnotherStorageImplementation example?

BR,
Ilkka

**Comment by yltsa** [comment]
Hi.. it is working now. 

I added udp_transport  variable to the BacnetClient constructor.

udp_transport = new BacnetIpUdpProtocolTransport(0xBAC0, false);
bacnet_client = new BacnetClient(udp_transport);

And then later:

udp_transport.Bvlc.AddBBMDPeer(BBMD, Mask);

Thank you very much for the great library.

BR,
Ilkka

**Comment by a1z5** [comment]
@yltsa can you elaborate your approach?

and can we use foreign device registration approach used in BasicReadWrite example instead of BBMD?

BBMD is already running in other network. I just wants to reach to that network.
